version: "3"
services:
  db:
    container_name: 'db'
    # image: atf.intranet.bb.com.br:5001/postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin123"
    ports:
      - "15432:5432"
    volumes:
      - ../pg:/var/lib/postgresql/data
  pgadmin:
    # image: atf.intranet.bb.com.br:5001/dpage/pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@root.com"
      PGADMIN_DEFAULT_PASSWORD: "admin123"
    ports:
      - "16543:80"
    depends_on:
      - db
  api:
    container_name: "api"
    build:
      context: .
    working_dir: /usr/api
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - 5050:5050
    volumes:
      - ./:/usr/api
      - /usr/api/node_modules
    depends_on:
      - db
      - pgadmin
    links:
      - db
volumes:
  api:
    driver: 'local'
  db:
    driver: 'local'